version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
#      - "6379:6379"
#  redis:
#    image: "redis:alpine"
#  redis-commander:
#    container_name: redis-commander
#    hostname: redis-commander
#    image: rediscommander/redis-commander:latest
#    restart: always
#    environment:
#    - REDIS_HOSTS=local:redis:6379
#    ports:
#    - "8181:8081"
