version: '3'
services:
 jenkins-server:
    image: jenkins/jenkins
    ports:
      - "50000:50000"
      - "8080:8080"
 jenkins-agent:
    image: jenkins/jnlp-slave
    environment:
      - url=http://jenkins-server:50000
#  redis-commander:
#    container_name: redis-commander
#    hostname: redis-commander
#    image: rediscommander/redis-commander:latest
#    restart: always
#    environment:
#    - REDIS_HOSTS=local:redis:6379
#    ports:
#    - "8181:8081"
